name: mufpga-analysis
channels:
  - defaults
dependencies:
  - python=3.8
  - nb_conda
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pip
  - pip:
    - scikit-learn
    - tifffile
    - read-roi
    - wget
